### ISSUE TITLE
Could not find file moveset_sfxconverted.dat

### ISSUE THREAD

**Issue by Justabrawlmodder** [squidgy617/BrawlInstallerPlugins#66]
![Screenshot (41)-01](https://user-images.githubusercontent.com/119655251/205236664-8e1b0e2e-2d08-42b6-a8c6-1363a371a3e5.jpeg)

**Comment by squidgy617** [comment]
Can you provide some more information on this issue?

**Comment by Justabrawlmodder** [comment]
When installing a character (using settings for vBrawl), I keep getting an error when it begins to make files for the soundbank using the Sawnd ID Replace Assist and SFX files from the Porting Tools. Here is the character for reference: https://www.mediafire.com/file/rzb8xsv7x8m5cor/Cloud.zip/file

**Comment by squidgy617** [comment]
Thank you. I will try to see if I can replicate it when I get the chance.

Could you also tell me what the settings `addSevenToSoundbankName` and `addSevenToSoundbankId` are in your build? You can see this in the settings.ini file in your build.

Additionally, if you're able to upload the log.txt file located in the `Logs` folder in your BrawlCrate directory, that should help me narrow the issue down.

My suspicion is this is an issue specific to vBrawl builds or related to the above settings I mentioned.

**Comment by Justabrawlmodder** [comment]
https://drive.google.com/drive/folders/1k2SwESaJZ2bHKv-XeNWXwkOaLi15ZDpR
Here is both the settings.ini and log.txt files.

**Comment by squidgy617** [comment]
I see the problem @Justabrawlmodder. You have the sfxChangeExe and sawndReplaceExe settings mixed up. You'll need to swap them.

Currently you have:
`sawndReplaceExe = C:\Users\brian\Downloads\Porting_Tools\SFX\sfxchange.exe`

`sfxChangeExe = C:\Users\brian\Downloads\lSIDRA_-_v1.2.0\lSIDRA - Version 1.2.0\lavaSawndIDReplaceAssist.exe`

You'll want to change these to:
`sawndReplaceExe = C:\Users\brian\Downloads\lSIDRA_-_v1.2.0\lSIDRA - Version 1.2.0\lavaSawndIDReplaceAssist.exe`

`sfxChangeExe = C:\Users\brian\Downloads\Porting_Tools\SFX\sfxchange.exe`

**Comment by Justabrawlmodder** [comment]
The error stop showing up, but now I am getting "Cannot convert int(-1) to byte".

**Comment by squidgy617** [comment]
Could you send me the `log.txt` file again?

**Comment by Justabrawlmodder** [comment]
Put the updated log.txt in the drive folder along with the settings.ini

**Comment by squidgy617** [comment]
By chance, in the info2 folder of your build, is there a file named `info.pac`, or only one named `info_en.pac`?

BrawlInstaller at this time only looks for the generic `info.pac` and not the english-only `info_en.pac`. It looks like it successfully found some other files such as `sc_selcharacter.pac` in your build (or at least I think it did), but I think it may not be finding `info.pac`. If this is indeed the problem, you could potentially resolve it by simply renaming `info_en.pac` to `info.pac`.

**Comment by Justabrawlmodder** [comment]
First, info.pac was missing, so I put in the build. I got the message now saying that the install was a success. However, when I boot the game up it never loads to the opening. I put a updated log.txt and a zip of the SD in the drive.

**Comment by Justabrawlmodder** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/119655251/205472278-72497c3c-9861-41d0-a0e9-14e52012c6ed.png)
Second, I do know this was showing up during the install of a character and wondered if this is part of the problem.

**Comment by squidgy617** [comment]
Yeah, the Cloud character package only includes a portrait name in the Project M format, so if you're using vBrawl cosmetics, that won't be installed automatically. However, at least in most modern builds, having a character who is missing a portrait name _shouldn't_ generally cause issues - it'll just mean their name will show as someone else's on CSS. That said, I don't know if there are Gecko codes or something that most builds use to handle this.

I can take a look at the SD sometime soon. That said, it may be hard to narrow the issue down with a vBrawl build. It is worth noting that I believe that character is designed for Project+, and may not be fully compatible with vBrawl, though I do not know if that would cause a crash on launch or would just cause issues in matches.

In any case, I will try taking a look at your SD.zip when I get the chance, and hopefully we can sort out where the incompatibility lies so this tool can fully support your build.

**Comment by squidgy617** [comment]
@Justabrawlmodder I took a look at the files. Is this all that's on your SD card? BrawlInstaller will only work with BrawlEx builds, and though I could be wrong, I am pretty sure there are several codes you need in your build such as the File Patch code in order for the build to function as a BrawlEx build. I don't see any such things in your SD.zip. There may be other things missing as well.

You can learn more about BrawlEx [here](http://forums.kc-mm.com/index.php?topic=65113.0), though that is the original version. It's recommended to use BrawlInstaller with modern builds such as [P+Ex](https://docs.google.com/document/d/1mAoVGymOkL3FwiMxfEt1V24qxnAWiO8I66G3zlU0ij8/edit) instead as the tool is primarily geared toward such builds, though in theory it should work with a standard BrawlEx build as well.

**Comment by Justabrawlmodder** [comment]
The reason I was trying to do a BrawlEx build in vBrawl was that I was hoping to keep the feeling of the original brawl without the changes Project M makes to the overall game. I did use the guides listed in Brawl Vault to make the SD folder. I have the File Patch code in my build as well. Could you send what you have set up for a vBrawl build to use BrawlInstaller?

**Comment by squidgy617** [comment]
Unfortunately I do not have a vBrawl build to provide you.

Unfortunately the Cloud character package you're trying to install is for Project M/Project+ builds so it will not work. You'd have to use a Brawl version of the character instead, to my knowledge no character package exists for that however.

I would start by using a Brawl-compatible character. If you still get crashes after successfully installing such a character, that narrows down the issue. I don't think any character packages currently exist for vBrawl characters however, so you would have to package one yourself.

**Comment by squidgy617** [comment]
Closing this issue since the original problem was resolved and the current problem appears to be fighter-related.
