### ISSUE TITLE
Can I use this for vbrawl extended edition

### ISSUE THREAD

**Issue by UncommonDX** [squidgy617/BrawlInstallerPlugins#85]
Hi i didn't know any other way to contact you sorry. But is there any way i can use this for vbrawl extended edition?
![bandicam 2023-02-06 16-40-33-132](https://user-images.githubusercontent.com/124632593/217093218-b5647fa2-15a9-47a4-8c80-8fa03e1eef9d.jpg)

**Comment by squidgy617** [comment]
I am not sure. It has only been tested with modern builds, so I can't say that vBrawl Extended edition is officially supported at this time. You may be able to get it working if you configure your build settings correctly, however it is unlikely I will be able to support if you run into issues as I do not have a vBrawl build to test with.

**Comment by UncommonDX** [comment]
If you would like I could send you one

**Comment by squidgy617** [comment]
Appreciate the offer but if I need one I can get one myself. If you have specific issues feel free to report them. Closing this issue since it's not really an issue.
