### ISSUE TITLE
Cannot insert any Character Packages without aborting error

### ISSUE THREAD

**Issue by TheFireHedgie** [squidgy617/BrawlInstallerPlugins#94]
This is my 1st time here, and I was very exited about adding new characters to my Brawl roster. However, whenever I try installing a character, no matter if downloaded or homemade, always abort on an error. First, I get tons of ''File does not exist'' errors, then ''Cannot convert int(-1) to Byte'' shows up... and then the installation aborts. It does that with EVERY character package I try to insert, so I kinda lost hope to add new fighters... Ah, here's the packages files I tried to use today. Have I done something wrong while opening them with BrawlCrate? I have v0.40a, by the way.
[Cloud.zip](https://github.com/squidgy617/BrawlInstallerPlugins/files/12248778/Cloud.zip)
[Sephiroth.zip](https://github.com/squidgy617/BrawlInstallerPlugins/files/12248780/Sephiroth.zip)
[Sora.zip](https://github.com/squidgy617/BrawlInstallerPlugins/files/12248782/Sora.zip)

**Comment by squidgy617** [comment]
What type of build are using, what are your build settings, and is your default build path correct?

**Comment by TheFireHedgie** [comment]
Hi! I am using BrawlCrate .0.40a, your latest plugins, Python 3.11.4, build folder path is C:\Project+ (also has a ''pf'' folder inside with evey other folder required), Python path is C:\Users\Dave\AppData\Local\Programs\Python\Python311-32\Lib , path for F# is C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\fsi.exe
...and everything fails, even when running BrawlCrate in Admin mode. It stops at Cosmetic3F, so perhaps the problem is there? I made another ZIP file of Sora while fixing everything, as I only use vBrawl and P+. Are you able to install it on your PC and Wii? Is there something I'm doing wrong? Please let me know.
[Sora v2.zip](https://github.com/squidgy617/BrawlInstallerPlugins/files/12271544/Sora.v2.zip)

**Comment by squidgy617** [comment]
If you're using Project+, character packages won't work. Project+ is not a BrawlEx build, and therefore can't have Ex characters added to it. You should use P+Ex as it is essentially Project+ with the BrawlEx engine integrated.

**Comment by TheFireHedgie** [comment]
Thank you. I finally got to install over 10 characters with success. But, when I load a match with them, the screen goes black with hex numbers on it (like an error/death screen), and freezes P+EX. In other words, I still cannot play with custom characters. I wonder why, though...

**Comment by squidgy617** [comment]
Most likely you have hit a file size limit. [This guide](https://docs.google.com/document/d/1sgA3Lr5IC4IVLWmuJOFLWj_FyKG7tP7jJy49eWTR_Z4/edit#heading=h.kileier2155b) lists some of the files and their limits, and goes over how to reduce the file sizes.

If it's only upon starting a match, my guess is `info.pac` has gotten too big.

If that's not it, the other thing to check would be if your cosmetics are the wrong size. CSPs, BPs, and stock icons should be the same size as the ones in P+. You don't want to use HD images for those.

**Comment by TheFireHedgie** [comment]
Hi! Sorry for the slow reply. There were violent thunderstorms where I lived, so I couldn't use my PC at all. My stupid PC forced me to format my SD card before re-using it, so I did that, then put the same files back on it, but now Project+ no longer loads; even with the right files being put back on the SD Card, it loads regular Brawl instead... I also learned that soundbanks need to be made from scratch to avoid using another one's; for example, Ike and Cloud are clones, so unless something is done, I can't have both Cloud and Ike's voices at the same time. I tried renaming the .sawnd files and fixing the FighterConfig files, either the cloned character does no sounds then crashes the game with the ''horn of death'' after 10 seconds, or silently freezes Wii after choosing a stage... Yikes. Oh well...at least I did my best, but still somewhat sad that I couldn't figure out how everything works.

**Comment by squidgy617** [comment]
You don't need to do that with modern soundbanks. Most modern characters use ex soundbank IDs, and BrawlInstaller has the ability to resolve soundbank ID conflicts. I'm not sure which version of Cloud you're using here, but if you're using the one I created on the vault, you should have no soundbank issues when in matches with Ike.

As for your issues with Project+, that's unrelated from the plugins so I can't help you there, but do remember that you can only install characters to P+Ex, not regular Project+.

**Comment by squidgy617** [comment]
Going to close this issue since it sounds like the initial problem was resolved and new problems sound build-related. Feel free to reopen or open a new issue if you need additional support.
